#!/bin/sh

dir="$(dirname $0)"
config="${dir}/config.sh"
letsconfig_sh="${dir}/letsencrypt.sh"

basedir="{1}"
email="${2}"
domain="${3}"

cat > ${config} << EOF
CHALLENGETYPE="http-01"
BASEDIR="${basedir}"
CONTACT_EMAIL="${email}"
EOF

exec "${letsconfig_sh}" --config "${config}" --domain "${domain}"